### ISSUE TITLE
AWS region for deployments service is fixed to us-east-1

### ISSUE THREAD

**Issue by fabianmp** [mendersoftware/mender-helm#18]
The chart does not provide a method to specify the AWS region, which defaults to us-east-1.
This causes an error in our deployment because our Kubernetes cluster is running in a different region.

Since the region can be overridden for the deployments service by setting the environment variable DEPLOYMENTS_AWS_REGION I suggest to add this option similar to the other S3 settings (e.g. AWS_BUCKET).

**Comment by tranchitella** [comment]
Thanks for your report @fabianmp, I'll take care of it.

**Comment by tranchitella** [comment]
Merged to master
