### ISSUE TITLE
not able to login after kubectl port-forward

### ISSUE THREAD

**Issue by nucatus** [mendersoftware/mender-helm#20]
Installed clean copy of mender using helm 3.5.2 using the external mongodb and minio services.

Since I don't run kubectl as root on the dev machine, the port-forward command is: `kubectl port-forward api-gateway-xxxx 8443:443`. This gets me a login screen after acknowledging in the browser the use of a self-signed certificate. 

I created a user by getting a shell into the running useradm pod as follows: `kbuectl -it exec useradm-xxxxxx -- /bin/sh`. In that shell I run the command `useradm create-user --username "demo@mender.io" --password "demodemo"` and I get a confirmation that the user is created by receiving an UUID of the user after running the create-user command.

However, I'm not able to login with this user. In the logs of the useradm pod I see the login request which is answered with a 400 response. No other information is provided to track the issue.

```
127.0.0.1 - demo@mender.io [01/Mar/2021:17:46:10 +0000] "POST /api/management/v1/useradm/auth/login HTTP/1.1" 400 179 "https://localhost:8443/ui/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:86.0) Gecko/20100101 Firefox/86.0" "-" request ID "-" 0.000
```

All the pods look to be in good state and no errors are reported.

```
mongodb-d95b77f69-hptlm                  1/1     Running   0          3d2h
minio-6b655dc8fb-5hmv8                   1/1     Running   0          3d2h
workflows-worker-797cc69cd7-kzzp2        1/1     Running   0          3d2h
inventory-8445865ff5-ghmg7               1/1     Running   0          3d2h
gui-6df6bf778d-k7xb7                     1/1     Running   0          3d2h
create-artifact-worker-86cc8857c-8gwdr   1/1     Running   0          3d2h
useradm-597884b94b-n9wzx                 1/1     Running   0          3d2h
api-gateway-6c48b5dc97-8ttts             1/1     Running   0          3d2h
workflows-server-5576d996d7-c8ffc        1/1     Running   0          3d2h
device-auth-7c48b7f4bb-7d6n5             1/1     Running   0          3d2h
deployments-7888c7589f-54ns9             1/1     Running   0          3d2h
```

**Comment by nucatus** [comment]
Well, in the end I managed to update those ports using `values.yaml` file. However, this doesn't fix the issue, because the ports are updated on the SVC that reverse proxies the api-gateway pod, and not on the pod itself. The `kubectl port-forward` command is executed on the pod, thus still having the 443 and 80 ports. For testing purposes, I ran the `kubectl port-forward` command with privileged user rights.

**Comment by tranchitella** [comment]
@nucatus the API gateway will block API requests coming from the UI if there is a port mismatch. We recently (aka, few hours ago) upgraded the Helm chart to the latest Mender release (2.6.0), may I ask you to give it a try and see if it solves your issue?

**Comment by nucatus** [comment]
@tranchitella, after the upgrade to 2.6.0, the port-forward works. However, the forward rule implemented in the web server does take into account the port. For instance, if I forward the remote port 443 to a local port 8443 and I go to https://lcaolhost:443, I will get forwarded to https://localhost/ui, instead of being forwarded to https://localhost:8443/ui.

However, if I manually enter https://localhost:8443/ui, the application is brought up. I guess this is a minor issue.

**Comment by tranchitella** [comment]
Thanks @nucatus, I confirm this is a (known) minor issue in the UI and not a Helm chart-specific issue.
I'm therefore closing this issue, as the original issue is addressed.
