### ISSUE TITLE
allow api-gateway to run without SSL termination

### ISSUE THREAD

**Issue by nucatus** [mendersoftware/mender-helm#24]
api-gateway is configured to always run with SSL termination. However, in case SSL termination is implemented in an upstream ingress controller, api-gateway should be run without SSL termination.

The underlying api-gateway container already has the ability to run without SSL termination, therefor it is just a matter of passing an environment variable to the container to signal this state to the container.

Created PR #25 to address this issue.

**Comment by tranchitella** [comment]
Thanks for your contribution, @nucatus. I merged your PR.

**Comment by nucatus** [comment]
I realized there is still a modification to be included with this change, namely to have the `api-gateway-svc.yaml` template disable the SSL port mapping to the back-end pod in case SSL is not enabled. I will implement it and create a new PR. Thanks.
