### ISSUE TITLE
api-gateway should allow non-SSL setup

### ISSUE THREAD

**Issue by nucatus** [mendersoftware/mender-helm#37]
In case no SSL termination is desired in the api-gateway service, that should be possible by setting the `api_gateway.env.SSL` variable to false. Whilst some of the SSL components are disabled using this variable, after the replacement of api-gateway implementation with traefik, the functionality was not brought up in line with the previous implementation, thus lacking the possibility to disable the SSL termination.

Pull request #31 was submitted to fix this issue.

**Comment by tranchitella** [comment]
PR was merged
