### ISSUE TITLE
Custom Signed Certificate not taken into effect by API Gateway / UI

### ISSUE THREAD

**Issue by garygan89** [mendersoftware/mender-helm#46]
I am trying to serve the API Gateway using a custom signed certificate with my own private CA,  instead of the default. Even after setting the `api_gateway.certs` and `api_gateway.key`, the API server and UI still use the self-sign cert by Traefik CA.

The default self-sign certificate presented by API Gateway/UI server:
![image](https://user-images.githubusercontent.com/2649703/127400829-c8c5c0bc-c413-4001-9883-42842aeb13b9.png)

**Comment by tranchitella** [comment]
@garygan89 sorry I just noticed the issue you posted here on GitHub.
Please post your questions to hub.mender.io, where you get way more visibility than here.
